name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Clean
        run: xcodebuild -scheme OpenVanilla -configuration Release clean
      - name: Clean
        run: xcodebuild -scheme OpenVanillaInstaller -configuration Release clean
      - name: Build
        run: xcodebuild -scheme OpenVanilla -configuration Release build
      - name: Build
        run: xcodebuild -scheme OpenVanillaInstaller -configuration Release build

